### ISSUE TITLE
Incomplete Reactor Simulations

### ISSUE THREAD

**Issue by rgillis8** [ReactionMechanismGenerator/pyrms#4]
I often run into the problem where the the solution will not run over the full time length of the system that I am running. See for example...
![image](https://user-images.githubusercontent.com/17207564/56152696-6a944580-5f82-11e9-85ee-6221c4313d84.png)
Note the y axis (and the solution in general) only goes till time 0.0006.

Today I encountered some strange behavior that I think isn't physical, but I need to play around with it more. I also haven't adjusted tolerances or anything for this. See for example...
![image](https://user-images.githubusercontent.com/17207564/56152664-55b7b200-5f82-11e9-9ed1-341e5d226c35.png)

**Comment by mjohnson541** [comment]
These two are the same simulations just with different end times?

**Comment by rgillis8** [comment]
That is correct. Although I have encountered the first issue with many different models.

**Comment by mjohnson541** [comment]
This may be due to settings in diffeqpy I'll take a look.

**Comment by mjohnson541** [comment]
I'm having trouble reproducing it can you send me the .rms file or the chem_annotated and species dictionary?

**Comment by mjohnson541** [comment]
For the second issue what kind of simulation is it?

**Comment by rgillis8** [comment]
Sure. All simulations are all ideal gas, constantTP simulations. I have emailed you the chem.rms file that I believe is associated with this.

**Comment by mjohnson541** [comment]
What are your simulation conditions?

**Comment by rgillis8** [comment]
![image](https://user-images.githubusercontent.com/17207564/56160143-62dd9c80-5f94-11e9-9854-bbe1e7beee87.png)

**Comment by mjohnson541** [comment]
Ok, so the first one isn't a problem with RMS, it's a problem with diffeqpy not displaying warning messages.  Regardless of whether the solution failed or succeeded, it gives you a solution object with the part of the solution it succeeded in simulating.  In Julia that's accompanied by a warning message, but that may not be the case in the wrapper (diffeqpy).  You should be able to check solution validity for now with `sol.retcode`.  

I had to mess with the tolerances a bit to get it to solve, but at 1e-16 abs and 1e-6 rel I have:  
![index](https://user-images.githubusercontent.com/7773228/56161119-c49f0600-5f96-11e9-93a0-439f44f0ebf3.png)
